const products = {
  grocery: [
    {
      id: "g1",
      name: "Fresh Organic Apples",
      price: 4.99,
      image:"./images/products/Grocery/apple.png", 
      rating: 4.5,
      reviews: 128,
    },
    {
      id: "g2",
      name: "Whole Grain Bread",
      price: 3.49,
      image: "./images/products/Grocery/bread.jpeg",
      rating: 4.2,
      reviews: 95,
    },
    {
      id: "g3",
      name: "Organic Milk",
      price: 2.99,
      image: "./images/products/Grocery/milk.jpeg",
      rating: 4.8,
      reviews: 210,
    },
    {
      id: "g4",
      name: "Free-Range Eggs",
      price: 4.49,
      image: "./images/products/Grocery/eggs.jpeg",
      rating: 4.6,
      reviews: 175,
    },
    {
      id: "g5",
      name: "Organic Quinoa",
      price: 6.99,
      image: "./images/products/Grocery/quinoa.jpeg",
      rating: 4.3,
      reviews: 88,
    },
    {
      id: "g6",
      name: "Extra Virgin Olive Oil",
      price: 12.99,
      image: "./images/products/Grocery/oliveoil.png  ",
      rating: 4.7,
      reviews: 156,
    },
    {
      id: "g7",
      name: "Fresh Avocados",
      price: 5.99,
      image: "./images/products/Grocery/avoado.jpeg",
      rating: 4.9,
      reviews: 203,
    },
    {
      id: "g8",
      name: "Organic Honey",
      price: 8.99,
      image: "./images/products/Grocery/honey.jpeg",
      rating: 4.8,
      reviews: 167,
    },
    {
      id: "g9",
      name: "Fresh Spinach",
      price: 3.49,
      image: "./images/products/Grocery/spinach.jpeg",
      rating: 4.4,
      reviews: 112,
    },
    {
      id: "g10",
      name: "Greek Yogurt",
      price: 4.99,
      image: "./images/products/Grocery/yogurt.jpeg",
      rating: 4.6,
      reviews: 189,
    },
    {
      id: "g11",
      name: "Bananas",
      price: 1.99,
      image: "./images/products/Grocery/banana.jpeg",
      rating: 4.5,
      reviews: 145,
    },
    {
      id: "g12",
      name: "Ketchup",
      price: 2.49,
      image: "./images/products/Grocery/ketchup.png",
      rating: 4.3,
      reviews: 101,
    }
  ],
  pharmaceutical: [
    {
      id: "p1",
      name: "Multivitamin Tablets",
      price: 15.99,
      image: "./images/products/Pharma/multivitamin.png",
      rating: 4.4,
      reviews: 112,
    },
    {
      id: "p2",
      name: "Painkillers",
      price: 7.49,
      image: "./images/products/Pharma/Painkillers.jpg",
      rating: 4.6,
      reviews: 203,
    },
    {
      id: "p3",
      name: "First Aid Kit",
      price: 24.99,
      image: "./images/products/Pharma/firstaid.jpeg",
      rating: 4.8,
      reviews: 87,
    },
    {
      id: "p4",
      name: "Hand Sanitizer",
      price: 3.99,
      image: "./images/products/Pharma/sanitizer.jpg",
      rating: 4.5,
      reviews: 176,
    },
    {
      id: "p5",
      name: "Vitamin C Supplements",
      price: 12.99,
      image: "./images/products/Pharma/vitc.jpeg",
      rating: 4.7,
      reviews: 145,
    },
    {
      id: "p6",
      name: "Digital Thermometer",
      price: 19.99,
      image: "./images/products/Pharma/thermometer.jpeg",
      rating: 4.3,
      reviews: 92,
    },
    {
      id: "p7",
      name: "Allergy Relief Medication",
      price: 8.99,
      image: "./images/products/Pharma/allergy.jpeg",
      rating: 4.5,
      reviews: 134,
    },
    {
      id: "p8",
      name: "Omega-3 Fish Oil",
      price: 14.99,
      image: "./images/products/Pharma/omega3.jpg",
      rating: 4.6,
      reviews: 167,
    },
    {
      id: "p9",
      name: "Bandaids",
      price: 1.99,
      image: "./images/products/Pharma/bandaids.jpg",
      rating: 4.4,
      reviews: 103,
    },
    {
      id: "p10",
      name: "Facial Cleanser",
      price: 14.75,
      image: "./images/products/Pharma/cleanser.jpg", 
      rating: 4.7,
      reviews: 189,
    },
  ],
  stationery: [
    {
      id: "s1",
      name: "Spiral Notebook",
      price: 3.99,
      image: "./images/products/Stationery/notebook.jpeg",
      rating: 4.6,
      reviews: 118,
    },
    {
      id: "s2",
      name: "Ballpoint Pen Set",
      price: 6.99,
      image: "./images/products/Stationery/penset.jpeg",
      rating: 4.7,
      reviews: 156,
    },
    {
      id: "s3",
      name: "Desk Organizer",
      price: 19.99,
      image: "./images/products/Stationery/organizer.jpeg",
      rating: 4.4,
      reviews: 83,
    },
    {
      id: "s4",
      name: "Sticky Notes Pack",
      price: 5.99,
      image: "./images/products/Stationery/stickynotes.jpeg",
      rating: 4.3,
      reviews: 97,
    },
    {
      id: "s5",
      name: "Scientific Calculator",
      price: 14.99,
      image: "./images/products/Stationery/calc.jpg",
      rating: 4.8,
      reviews: 124,
    },
    {
      id: "s6",
      name: "Mechanical Pencil Set",
      price: 9.99,
      image: "./images/products/Stationery/mechanicalpencils.jpg",
      rating: 4.5,
      reviews: 108,
    },
    {
      id: "s7",
      name: "Binder Clips",
      price: 4.99,
      image: "./images/products/Stationery/clips.jpeg",
      rating: 4.2,
      reviews: 76,
    },
    {
      id: "s8",
      name: "Colored Pencil Set",
      price: 11.99,
      image: "./images/products/Stationery/coloredpencils.jpeg",
      rating: 4.6,
      reviews: 132,
    },
    {
      id: "s9",
      name: "Whiteboard Markers",
      price: 7.99,
      image: "./images/products/Stationery/whiteboardmarkers.jpeg",
      rating: 4.4,
      reviews: 91,
    },
    {
      id: "s10",
      name: "Stapler and Staples Set",
      price: 8.49,
      image: "./images/products/Stationery/stapler.jpeg",
      rating: 4.3,
      reviews: 87,
    },
  ],
  misc: [
    {
      id: "m1",
      name: "Empty DVD's",
      price: 4.99,
      image: "./images/products/Misc/dvd.jpeg", 
      rating: 4.5,
      reviews: 213,
    },
    {
      id: "m2",
      name: "Stainless Steel Water Bottle",
      price: 24.99,
      image: "./images/products/Misc/bottle.jpeg",
      rating: 4.7,
      reviews: 178,
    },
    {
      id: "m3",
      name: "Board Game Set",
      price: 34.99,
      image: "./images/products/Misc/boardgames.jpeg",
      rating: 4.6,
      reviews: 95,
    },
    {
      id: "m4",
      name: "T-Shirt",
      price: 19.99,
      image: "./images/products/Misc/t-shirt.jpeg",
      rating: 4.3,
      reviews: 142,
    },
    {
      id: "m5",
      name: "LED strips",
      price: 15.99,
      image: "./images/products/Misc/LED.jpeg",
      rating: 4.4,
      reviews: 87,
    },
    {
      id: "m6",
      name: "Yoga Mat",
      price: 29.99,
      image: "./images/products/Misc/mat.jpeg",
      rating: 4.8,
      reviews: 156,
    },
    {
      id: "m7",
      name: "Bluetooth Speaker",
      price: 39.99,
      image: "./images/products/Misc/speaker.jpeg",
      rating: 4.6,
      reviews: 189,
    },
    {
      id: "m8",
      name: "Scented Candle Set",
      price: 30.45,
      image: "./images/products/Misc/candles.jpg",
      rating: 4.7,
      reviews: 124,
    },
    {
      id: "m9",
      name: "Leather Wallet",
      price: 32.99,
      image: "./images/products/Misc/wallet.jpg",
      rating: 4.5,
      reviews: 112,
    },
    {
      id: "m10",
      name: "Portable Power Bank",
      price: 27.99,
      image: "./images/products/Misc/powerbank.jpeg",
      rating: 4.4,
      reviews: 167,
    },
  ],
}

console.log("Data.js loaded, products:", products)

